=== milosavljevicdj/ist2021/proizvodi.dtd
<!ELEMENT Proizvodi (Proizvod)+>
<!ELEMENT Proizvod (Kategorija,Cena,Tekst,Oznaka+,Akcija+)>
<!ELEMENT Kategorija (#PCDATA)>
<!ELEMENT Cena (#PCDATA)>
<!ELEMENT Tekst (#PCDATA)>
<!ELEMENT Oznaka (#PCDATA)>
<!ELEMENT Akcija (#PCDATA)>

<!ATTLIST Kategorija imeKategorije (Laptop | Monitor | Sto | Stolica) #REQUIRED>
<!ATTLIST Cena valuta (RSD | EUR)  #REQUIRED>
<!ATTLIST Akcija Cena CDATA #REQUIRED>
<!ATTLIST Akcija DatumIsteka CDATA #REQUIRED>

=== milosavljevicdj/ist2021/proizvodi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Proizvodi SYSTEM "proizvodi.dtd">
<Proizvodi>
<Proizvod>
    <Kategorija imeKategorije='Laptop'/>
    <Cena valuta='RSD'>60000</Cena>
    <Tekst> ASUS N55S, 8GB RAM, Intel i7 CPU </Tekst>
    <Oznaka>Laptop</Oznaka>
    <Akcija Cena='55000' DatumIsteka='25-08-2021'/>
    <Akcija Cena='51000' DatumIsteka='25-10-2021'/>
</Proizvod>
<Proizvod>
    <Kategorija imeKategorije='Monitor'/>
    <Cena valuta='RSD'>10000</Cena>
    <Tekst>Monitor ASUS HT</Tekst>
    <Oznaka>Monitor</Oznaka>
    <Oznaka>ASUS</Oznaka>
    <Akcija Cena='10000' DatumIsteka='17-08-2021'></Akcija>
</Proizvod>
<Proizvod>
    <Kategorija imeKategorije='Sto'/>
    <Cena valuta='RSD'>15000</Cena>
    <Tekst>Radni sto 305x170</Tekst>
    <Oznaka>Sto</Oznaka>
    <Oznaka>Drveni</Oznaka>
    <Akcija Cena='15000' DatumIsteka='24-08-2021'></Akcija>
</Proizvod>
<Proizvod>
    <Kategorija imeKategorije='Stolica'/>
    <Cena valuta='RSD'>8000</Cena>
    <Tekst>Stolica za racunar</Tekst>
    <Oznaka>Stolica</Oznaka>
    <Oznaka>Plasticna</Oznaka>
    <Akcija Cena='8000' DatumIsteka='17-08-2021'></Akcija>
</Proizvod>
</Proizvodi>
